version: '3'
services:
  mflight-api:
    build: .
    ports:
      - 5001:5000
    environment:
      APP_PORT: "5000"
      APP_MFLIGHT_URL: "http://192.168.1.10:56002"
      APP_MFLIGHT_MOBILE_ID: ${APP_MFLIGHT_MOBILE_ID}
      APP_MFLIGHT_CACHE_TTL: "5s"
