// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go

// Package mock_application is a generated GoMock package.
package mock_application

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	domain "mflight-api/domain"
	reflect "reflect"
)

// MockMetricsCollector is a mock of MetricsCollector interface
type MockMetricsCollector struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsCollectorMockRecorder
}

// MockMetricsCollectorMockRecorder is the mock recorder for MockMetricsCollector
type MockMetricsCollectorMockRecorder struct {
	mock *MockMetricsCollector
}

// NewMockMetricsCollector creates a new mock instance
func NewMockMetricsCollector(ctrl *gomock.Controller) *MockMetricsCollector {
	mock := &MockMetricsCollector{ctrl: ctrl}
	mock.recorder = &MockMetricsCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMetricsCollector) EXPECT() *MockMetricsCollectorMockRecorder {
	return m.recorder
}

// CollectLatestMetrics mocks base method
func (m *MockMetricsCollector) CollectLatestMetrics(ctx context.Context) (domain.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectLatestMetrics", ctx)
	ret0, _ := ret[0].(domain.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectLatestMetrics indicates an expected call of CollectLatestMetrics
func (mr *MockMetricsCollectorMockRecorder) CollectLatestMetrics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectLatestMetrics", reflect.TypeOf((*MockMetricsCollector)(nil).CollectLatestMetrics), ctx)
}

// CollectTimeSeriesMetrics mocks base method
func (m *MockMetricsCollector) CollectTimeSeriesMetrics(ctx context.Context) (domain.TimeSeriesMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectTimeSeriesMetrics", ctx)
	ret0, _ := ret[0].(domain.TimeSeriesMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectTimeSeriesMetrics indicates an expected call of CollectTimeSeriesMetrics
func (mr *MockMetricsCollectorMockRecorder) CollectTimeSeriesMetrics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectTimeSeriesMetrics", reflect.TypeOf((*MockMetricsCollector)(nil).CollectTimeSeriesMetrics), ctx)
}
