name: Publish Docker Image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  push_to_registry:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=otknoy/mflight-api
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PR=PR${{ github.event.number }}
            TAGS=${DOCKER_IMAGE}:${PR}-$(date +%Y%m%d-%H%M%M)
            TAGS=${TAGS},${DOCKER_IMAGE}:${PR}-$(date +%Y%m%d)
          elif [ "${{ github.event_name }}" = "push" ]; then
            TAGS=${DOCKER_IMAGE}:$(date +%Y%m%d-%H%M%M)
            TAGS=${TAGS},${DOCKER_IMAGE}:latest
          fi
          echo ::set-output name=tags::${TAGS}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.prepare.outputs.tags }}
