name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.6

    - name: Build
      run: go build -v app/main.go

    - name: Test
      run: go test -v -cover ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.44.1
